### ISSUE TITLE
XXAIMLのloadを固定にする

### ISSUE THREAD

**Issue by amyroi** [jagrament/xaiml-ruby#1]
## 概要
XXAIMLのloadを固定にする

### 内容
CI環境でclass loadの順番が保証されない為
require を固定にする

```
Bundler::GemRequireError: There was an error while trying to load the gem 'xaiml'.
Gem Load Error is: uninitialized constant XAIML::Document
```

**Comment by ghost** [comment]
@amyroi 
1-2行目は必要なのでしょうか？
https://github.com/jagrament/xaiml-ruby/pull/2/files#diff-9d98dfe55ba1ee7f29343e4353f8d0f9L2
